size : size.cpp
	g++ -O0 size.cpp -o size


line : line.cpp
	g++ -O0 line.cpp -o line


associate : associate.cpp
	g++ -O0 associate.cpp -o associate

matrix : matrix.cpp
	g++ -O0 matrix.cpp -o matrix
